"""Increase grade column length

Revision ID: 90ae9a34c73d
Revises: bd1a44bc253b
Create Date: 2026-07-08 09:34:04.661325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90ae9a34c73d'
down_revision: Union[str, Sequence[str], None] = 'bd1a44bc253b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scans', 'grade',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'N/A'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scans', 'grade',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=5),
               existing_nullable=False,
               existing_server_default=sa.text("'N/A'::character varying"))
    # ### end Alembic commands ###
