"""add report fields to scans

Revision ID: d3e938825830
Revises: 4661e0ef5601
Create Date: 2026-07-06 11:19:19.042632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3e938825830'
down_revision: Union[str, Sequence[str], None] = '4661e0ef5601'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.add_column(
        'scans',
        sa.Column(
            'grade',
            sa.String(length=5),
            nullable=False,
            server_default='N/A'
        )
    )

    op.add_column(
        'scans',
        sa.Column(
            'risk',
            sa.String(length=30),
            nullable=False,
            server_default='Unknown'
        )
    )

    op.add_column(
        'scans',
        sa.Column(
            'report',
            sa.JSON(),
            nullable=True
        )
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scans', 'report')
    op.drop_column('scans', 'risk')
    op.drop_column('scans', 'grade')
    # ### end Alembic commands ###
